version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    environment:
      POSTGRES_DB: olist-ecommerce-logistics-analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql
      - ./data/processed:/data/processed

volumes:
  postgres_data: